-- Tabelas do banco D1 (versão online). Já foram criadas no banco criatorio-sertori-db.
CREATE TABLE IF NOT EXISTS aves (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL, especie TEXT NOT NULL, cor TEXT NOT NULL, sexo TEXT NOT NULL, anilha TEXT, registro TEXT, idade REAL NOT NULL, criado_em DATETIME DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vacinas (id INTEGER PRIMARY KEY AUTOINCREMENT, ave_id INTEGER, nome_vacina TEXT NOT NULL, data_aplicacao DATE NOT NULL, proxima_dose DATE, observacoes TEXT);
CREATE TABLE IF NOT EXISTS nascimentos (id INTEGER PRIMARY KEY AUTOINCREMENT, mae_id INTEGER, pai_id INTEGER, data_nascimento DATE NOT NULL, quantidade INTEGER DEFAULT 1, observacoes TEXT);
CREATE TABLE IF NOT EXISTS backups (id INTEGER PRIMARY KEY AUTOINCREMENT, criado_em DATETIME DEFAULT CURRENT_TIMESTAMP, dados TEXT NOT NULL);
